/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cenfotec.componentes.control;

/**
 *
 * @author Dell
 */
public class MyCalculator extends javax.swing.JPanel {

    /**
     * Creates new form MyCalculator
     */
    public MyCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Result = new javax.swing.JLabel();
        Number1 = new javax.swing.JButton();
        Number2 = new javax.swing.JButton();
        Number3 = new javax.swing.JButton();
        Number4 = new javax.swing.JButton();
        Number6 = new javax.swing.JButton();
        Number5 = new javax.swing.JButton();
        Number7 = new javax.swing.JButton();
        Number8 = new javax.swing.JButton();
        Number9 = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        btnMultiple = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        Number0 = new javax.swing.JButton();

        setToolTipText("gvg");

        Result.setBackground(new java.awt.Color(255, 255, 255));
        Result.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result.setText("0");
        Result.setToolTipText("");
        Result.setAlignmentX(0.5F);
        Result.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        Number1.setText("1");
        Number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number1ActionPerformed(evt);
            }
        });

        Number2.setText("2");
        Number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number2ActionPerformed(evt);
            }
        });

        Number3.setText("3");
        Number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number3ActionPerformed(evt);
            }
        });

        Number4.setText("4");
        Number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number4ActionPerformed(evt);
            }
        });

        Number6.setText("6");
        Number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number6ActionPerformed(evt);
            }
        });

        Number5.setText("5");
        Number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number5ActionPerformed(evt);
            }
        });

        Number7.setText("7");
        Number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number7ActionPerformed(evt);
            }
        });

        Number8.setText("8");
        Number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number8ActionPerformed(evt);
            }
        });

        Number9.setText("9");
        Number9.setToolTipText("");
        Number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number9ActionPerformed(evt);
            }
        });

        btnPlus.setText("+");
        btnPlus.setToolTipText("Suma");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnMin.setText("-");
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });

        btnMultiple.setText("*");
        btnMultiple.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultipleActionPerformed(evt);
            }
        });

        btnCalculate.setText("Calcular");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnReset.setText("Resetear");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });

        Number0.setText("0");
        Number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Number1)
                                .addGap(18, 18, 18)
                                .addComponent(Number2)
                                .addGap(18, 18, 18)
                                .addComponent(Number3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Number4)
                                .addGap(18, 18, 18)
                                .addComponent(Number5)
                                .addGap(18, 18, 18)
                                .addComponent(Number6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Number7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Number0)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Number8)
                                        .addGap(18, 18, 18)
                                        .addComponent(Number9)))))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDivide)
                                    .addComponent(btnMin)))
                            .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number1)
                    .addComponent(Number2)
                    .addComponent(Number3)
                    .addComponent(btnPlus)
                    .addComponent(btnMin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMultiple)
                            .addComponent(btnDivide))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Number4)
                            .addComponent(Number5)
                            .addComponent(Number6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Number9)
                            .addComponent(Number8)
                            .addComponent(Number7))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number0))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void Number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number1ActionPerformed
        String valueNow = this.Result.getText();
        if (valueNow.length() == 1 && valueNow.equals("0")){
            this.Result.setText("1");
        } else {
            this.Result.setText(valueNow + "1");
        }
    }//GEN-LAST:event_Number1ActionPerformed

    private void Number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number2ActionPerformed
        String valueNow = this.Result.getText();
         if (valueNow.length() == 1 && valueNow.equals("0")){
            this.Result.setText("2");
        } else {
            this.Result.setText(valueNow + "2");
        }
    }//GEN-LAST:event_Number2ActionPerformed

    private void Number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number3ActionPerformed
        String valueNow = this.Result.getText();
         if (valueNow.length() == 1 && valueNow.equals("0")){
            this.Result.setText("3");
        } else {
            this.Result.setText(valueNow + "3");
        }
    }//GEN-LAST:event_Number3ActionPerformed

    private void Number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number4ActionPerformed
        String valueNow = this.Result.getText();
         if (valueNow.length() == 1 && valueNow.equals("0")){
            this.Result.setText("4");
        } else {
            this.Result.setText(valueNow + "4");
        }
    }//GEN-LAST:event_Number4ActionPerformed

    private void Number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number6ActionPerformed
        String valueNow = this.Result.getText();
        if (valueNow.length() == 1 && valueNow.equals("0")){
            this.Result.setText("6");
        } else {
            this.Result.setText(valueNow + "6");
        }
    }//GEN-LAST:event_Number6ActionPerformed

    private void Number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number5ActionPerformed
        String valueNow = this.Result.getText();
         if (valueNow.length() == 1 && valueNow.equals("0")){
            this.Result.setText("5");
        } else {
            this.Result.setText(valueNow + "5");
        }
    }//GEN-LAST:event_Number5ActionPerformed

    private void Number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number7ActionPerformed
        String valueNow = this.Result.getText();
        if (valueNow.length() == 1 && valueNow.equals("0")){
            this.Result.setText("7");
        } else {
            this.Result.setText(valueNow + "7");
        }
    }//GEN-LAST:event_Number7ActionPerformed

    private void Number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number8ActionPerformed
        String valueNow = this.Result.getText();
        if (valueNow.length() == 1 && valueNow.equals("0")){
            this.Result.setText("8");
        } else {
            this.Result.setText(valueNow + "8");
        }
    }//GEN-LAST:event_Number8ActionPerformed

    private void Number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number9ActionPerformed
        String valueNow = this.Result.getText();
         if (valueNow.length() == 1 && valueNow.equals("0")){
            this.Result.setText("9");
        } else {
            this.Result.setText(valueNow + "0");
        }
    }//GEN-LAST:event_Number9ActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        String valueNow = this.Result.getText();
        int valueLength = valueNow.length();
        if (valueLength != 0) {
            if (valueNow.substring(valueNow.length()-1,valueNow.length()).equals("+") || valueNow.substring(valueNow.length()-1,valueNow.length()).equals("-") || valueNow.substring(valueNow.length()-1,valueNow.length()).equals("/") || valueNow.substring(valueNow.length()-1,valueNow.length()).equals("*")) {
                valueNow = valueNow.substring(0, valueNow.length() - 1);
                this.Result.setText(valueNow + "+");
            } else {
                this.Result.setText(valueNow + "+");
            }
        }
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        String valueNow = this.Result.getText();
        int valueLength = valueNow.length();
        if (valueLength != 0) {
            if (valueNow.substring(valueNow.length()-1,valueNow.length()).equals("+") || valueNow.substring(valueNow.length()-1,valueNow.length()).equals("-") || valueNow.substring(valueNow.length()-1,valueNow.length()).equals("/") || valueNow.substring(valueNow.length()-1,valueNow.length()).equals("*")) {
                valueNow = valueNow.substring(0, valueNow.length() - 1);
                this.Result.setText(valueNow + "/");
            } else {
                this.Result.setText(valueNow + "/");
            }
        }
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        String valueNow = this.Result.getText();
        int valueLength = valueNow.length();
        if (valueLength != 0) {
            String value = valueNow.substring(valueNow.length()-1,valueNow.length());
            System.out.println(value);
            if (valueNow.substring(valueNow.length()-1,valueNow.length()).equals("+") || valueNow.substring(valueNow.length()-1,valueNow.length()).equals("-") || valueNow.substring(valueNow.length()-1,valueNow.length()).equals("/") || valueNow.substring(valueNow.length()-1,valueNow.length()).equals("*")) {
                valueNow = valueNow.substring(0, valueNow.length() - 1);
                this.Result.setText(valueNow + "-");
            } else {
                this.Result.setText(valueNow + "-");
            }
        }
    }//GEN-LAST:event_btnMinActionPerformed

    private void btnMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultipleActionPerformed
        String valueNow = this.Result.getText();
        int valueLength = valueNow.length();
        if (valueLength != 0) {
            if (valueNow.substring(valueNow.length()-1,valueNow.length()).equals("+") || valueNow.substring(valueNow.length()-1,valueNow.length()).equals("-") || valueNow.substring(valueNow.length()-1,valueNow.length()).equals("/") || valueNow.substring(valueNow.length()-1,valueNow.length()).equals("*")) {
                valueNow = valueNow.substring(0, valueNow.length() - 1);
                this.Result.setText(valueNow + "*");
            } else {
                this.Result.setText(valueNow + "*");
            }
        }
    }//GEN-LAST:event_btnMultipleActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        String value = this.Result.getText();
        String result;
        String operator = "";
        String[] numbers;

        if (value.length() == 0 ) {
            
        } else {
            for (char v : value.toCharArray()) {
                if (v == '+' || v == '-' || v == '/' || v == '*') {
                    operator = Character.toString(v);
                }
            }
            
            if (operator.equals("")){
                this.Result.setText("Incompleto!");
                this.Result.setText("0");

            } else {
                numbers = value.split(operator, 5);
                
                switch (operator) {
                    case "+":
                        result = Integer.toString(Integer.parseInt(numbers[0]) + Integer.parseInt(numbers[1]));
                        break;
                    case "-":
                        result = Integer.toString(Integer.parseInt(numbers[0]) - Integer.parseInt(numbers[1]));
                        break;
                    case "*":
                        result = Integer.toString(Integer.parseInt(numbers[0]) * Integer.parseInt(numbers[1]));
                        break;
                    case "/":
                        result = Integer.toString(Integer.parseInt(numbers[0]) / Integer.parseInt(numbers[1]));
                        break;
                    default:
                        result = "Error";
                        break;
                }

                this.Result.setText(result);
            }
        }

            



    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        this.Result.setText("0");
    }//GEN-LAST:event_btnResetMouseClicked

    private void Number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number0ActionPerformed
        // TODO add your handling code here:
        String valueNow = this.Result.getText();

        if (valueNow.length() != 1 && !valueNow.equals("0")){
            this.Result.setText(valueNow + "0");
        }
    }//GEN-LAST:event_Number0ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Number0;
    private javax.swing.JButton Number1;
    private javax.swing.JButton Number2;
    private javax.swing.JButton Number3;
    private javax.swing.JButton Number4;
    private javax.swing.JButton Number5;
    private javax.swing.JButton Number6;
    private javax.swing.JButton Number7;
    private javax.swing.JButton Number8;
    private javax.swing.JButton Number9;
    private javax.swing.JLabel Result;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnMultiple;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnReset;
    // End of variables declaration//GEN-END:variables
}
